force_keyboard_focus = false    # forces keyboard forcus to stay in Walker
close_when_open = true          # close walker when invoking while already opened
click_to_close = true           # closes walker if clicking outside of the main content area
single_click_activation = true  # activate items with a single click opposed to a double click
selection_wrap = false          # wrap list if at bottom or top
global_argument_delimiter = "#" # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
exact_search_prefix = "'"       # disable fuzzy searching
theme = "noctalia"              # theme to use
disable_mouse = false           # disable mouse (on input and list only)
debug = false                   # enables debug printing for some stuff, f.e. keybinds
page_jump_items = 10            # number of items to skip with Page Up/Down
hide_quick_activation = false   # globally hide the quick activation buttons
hide_action_hints = true        # globally hide the action hints
hide_action_hints_dmenu = true  # hide the actions hints for dmenu
hide_return_action = false      # hide actions that are bound to Return
resume_last_query = true        # open walker with the last query in place
actions_as_menu = false         # display all possible actions in a submenu

[shell]
anchor_top = false
anchor_bottom = false
anchor_left = false
anchor_right = false

[placeholders]
"default" = { input = "Search or ctrl+n|p", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"j

[keybinds]
next = ["Down", "ctrl n"]
previous = ["Up", "ctrl p"]
close = ["Escape", "ctrl q"]
quick_activate = ["h", "j", "k", "l"]
