[config]

[templates.kitty]
input_path = '~/.config/noctalia/templates/kitty.conf'
output_path = '~/.local/state/caelestia/theme/kitty.conf'
post_hook = 'kill -USR1 $(pidof kitty)'

[templates.zed]
input_path = '~/.config/noctalia/templates/zed.json'
output_path = '~/.local/state/caelestia/theme/zed.json'

[templates.librewolf]
input_path = '~/.config/noctalia/templates/librewolf.css'
output_path = '~/.local/state/caelestia/theme/librewolf.css'

[templates.m3scheme]
input_path = '~/.config/noctalia/templates/m3scheme.json'
output_path = '~/.local/state/caelestia/scheme.json'
